# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название динозавра')),
                ('info', models.URLField(verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название новости')),
                ('where_from', models.URLField(verbose_name='Источник')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('body', models.TextField()),
            ],
        ),
    ]
