# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
