# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя автора')),
                ('site', models.URLField(blank=True, verbose_name='Статья')),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название книги')),
                ('slug_name', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Коротко о книге')),
                ('info', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Издательство - год, и прочее')),
                ('site', models.URLField(blank=True, verbose_name='Статья')),
                ('about', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='test')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория новости')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True, verbose_name='Название отряда')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Статья')),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название сайта')),
                ('site', models.URLField(blank=True, verbose_name='Статья')),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название отряда')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Статья')),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dino',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dino',
            name='foto',
            field=models.ImageField(blank=True, upload_to='test'),
        ),
        migrations.AddField(
            model_name='new',
            name='dino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Dino'),
        ),
        migrations.AddField(
            model_name='new',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='test'),
        ),
        migrations.AddField(
            model_name='new',
            name='slug_name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Синапсис новости'),
        ),
        migrations.AlterField(
            model_name='dino',
            name='info',
            field=models.URLField(blank=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Загаловок новости'),
        ),
        migrations.AlterField(
            model_name='new',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время'),
        ),
        migrations.AlterField(
            model_name='new',
            name='where_from',
            field=models.URLField(blank=True, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='book',
            name='dino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Dino'),
        ),
        migrations.AddField(
            model_name='dino',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Order'),
        ),
        migrations.AddField(
            model_name='dino',
            name='suborder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.SubOrder'),
        ),
        migrations.AddField(
            model_name='new',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Cat'),
        ),
    ]
