# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='dino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Dino'),
        ),
        migrations.AlterField(
            model_name='dino',
            name='info',
            field=models.URLField(blank=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время'),
        ),
        migrations.AlterField(
            model_name='new',
            name='where_from',
            field=models.URLField(blank=True, verbose_name='Источник'),
        ),
    ]
