# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0002_auto_20170701_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='img',
            field=models.ImageField(blank=True, upload_to='test'),
        ),
    ]
