# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0002_auto_20170720_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dino',
            name='order',
        ),
        migrations.AddField(
            model_name='suborder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Order'),
        ),
    ]
