# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 16:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0002_auto_20170721_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
