# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 11:09
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinomania', '0005_auto_20170802_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('av', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='photos')),
                ('hobby', models.CharField(max_length=512, null=True, verbose_name='Интересы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
