# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0005_auto_20170716_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='new',
            name='img',
        ),
    ]
