# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0006_auto_20170716_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, upload_to='test'),
        ),
    ]
