# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinomania', '0008_new_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Загаловок новости')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='dino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Dino'),
        ),
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Издательство - год, и прочее'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug_name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Коротко о книге'),
        ),
        migrations.AddField(
            model_name='new',
            name='slug_name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Синапсис новости'),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Загаловок новости'),
        ),
        migrations.AddField(
            model_name='new',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinomania.Category'),
        ),
    ]
